DATA_FOLDER: '../data/raw/CXR8/CXR8/images/'
TARGET_FOLDER: '../data/raw/images'
FLATTENED_FOLDER: '../data/raw/flattened/'
TEST_IMAGES:  '../data/labels/test_labels_filtered.csv'
TRAIN_IMAGES: '../data/labels/train_labels_filtered.csv'

RANDOM_STATE: 42 # what else ;)
BATCH_SIZE: 16
IMAGE_SIZE: 32 # in pixels, e.g. 32 = 32x32 images
EPOCHS: 3

COLOR_SEQUENTIAL:   "inferno" # matplotlib color map (used for heatmaps)
COLOR_DISCRETE:     "Paired"  # matplotlib discrete set of colors (for statistical plots:  i.e. bar plots)